# Manifests management with kustomize

resources:
- k8s-manifests/app-node/deployment.yaml
- k8s-manifests/app-node/service.yaml
- k8s-manifests/app-python/deployment.yaml
- k8s-manifests/app-python/service.yaml
- k8s-manifests/nginx/deployment.yaml
- k8s-manifests/nginx/service.yaml
- k8s-manifests/ingress/app-ingress.yaml
- k8s-manifests/argocd/application.yaml
- k8s-manifests/ingress/argocd-ingress.yaml
- k8s-manifests/ingress/grafana-ingress.yaml

configMapGenerator:
- files:
  - k8s-manifests/nginx/nginx.conf
  name: nginx-config


images:
- name: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-node
  newName: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-node
  newTag: 53d8e4eb5794cae9e4c79100d0b3d70e7d5ba4e8
- name: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-python
  newName: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-python
  newTag: v1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
