# Manifests management with kustomize

resources:
- k8s-manifests/app-node/deployment.yaml
- k8s-manifests/app-node/service.yaml
- k8s-manifests/app-python/deployment.yaml
- k8s-manifests/app-python/service.yaml
- k8s-manifests/nginx/deployment.yaml
- k8s-manifests/nginx/service.yaml
- k8s-manifests/ingress/app-ingress.yaml
- k8s-manifests/argocd/application.yaml
- k8s-manifests/ingress/argocd-ingress.yaml
- k8s-manifests/ingress/grafana-ingress.yaml

configMapGenerator:
- files:
  - k8s-manifests/nginx/nginx.conf
  name: nginx-config


images:
- name: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-node
  newName: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-node
  newTag: 1f52f437cedf85cbdde9de2dadd07a9e879ca69c
- name: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-python
  newName: 547886934166.dkr.ecr.us-east-1.amazonaws.com/app-python
  newTag: 1f52f437cedf85cbdde9de2dadd07a9e879ca69c
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
